# Generated by Django 2.1.4 on 2019-01-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HPI_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2, verbose_name='STATE')),
                ('year', models.FloatField(verbose_name='YEAR')),
                ('qtr', models.IntegerField(verbose_name='QTR')),
                ('hpi', models.FloatField(verbose_name='HPI')),
            ],
        ),
    ]
