# Generated by Django 2.1.4 on 2019-05-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HPIplot', '0002_auto_20190103_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpi_state',
            name='cpi',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=100, verbose_name='CPI'),
        ),
    ]
