# Generated by Django 2.1.4 on 2019-01-02 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentcalc', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HPI_state',
        ),
    ]
