# Generated by Django 2.1.4 on 2019-01-27 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthlycalc', '0002_hpi_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HPI_state',
        ),
    ]
